slogan: 人生自是有情痴，此恨不关风与月

menu:
  - title: Archives
    url: archives
    intro: All the articles.
    icon: fa fa-archive
  - title: Categories
    url: categories
    intro: All the categories.
    icon: fa fa-folder
  - title: Tags
    url: tags
    intro: All the tags.
    icon: fa fa-tags
  - title: About
    url: about
    intro: About me.
    icon: fa fa-user

links:
  - title: My Github
    url: http://www.github.com/yely
    intro: My Github account.
    icon: fa fa-github
  - title: My weibo
    url: http://t.sina.com.cn/zjuhwc
    intro: My sina weibo account.
    icon: fa fa-weibo
  - title: Freemind
    url: https://github.com/wzpan/freemind/
    intro: Freemind's Github repository.
    icon: fa fa-github
	
widgets:
- search
- category
- tagcloud
- links
- map

#### Comment
duoshuo: 
  enable: true  ## duoshuo.com
  short_name: huwenchao    ## duoshuo short name.

rss: atom.xml
fancybox: true
favicon: img/logo.png
google_analytics: UA-49755189-1